from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela2(object):
    def setupUi(self, tela2):
        tela2.setObjectName("tela2")
        tela2.resize(699, 712)
        self.lep1 = QtWidgets.QLineEdit(tela2)
        self.lep1.setGeometry(QtCore.QRect(290, 28, 133, 20))
        self.lep1.setObjectName("lep1")
        self.lep2 = QtWidgets.QLineEdit(tela2)
        self.lep2.setGeometry(QtCore.QRect(290, 57, 133, 20))
        self.lep2.setObjectName("lep2")
        self.lep3 = QtWidgets.QLineEdit(tela2)
        self.lep3.setGeometry(QtCore.QRect(290, 86, 133, 20))
        self.lep3.setObjectName("lep3")
        self.lep4 = QtWidgets.QLineEdit(tela2)
        self.lep4.setGeometry(QtCore.QRect(290, 114, 133, 20))
        self.lep4.setObjectName("lep4")
        self.lep5 = QtWidgets.QLineEdit(tela2)
        self.lep5.setGeometry(QtCore.QRect(290, 145, 133, 20))
        self.lep5.setObjectName("lep5")
        self.lep6 = QtWidgets.QLineEdit(tela2)
        self.lep6.setGeometry(QtCore.QRect(290, 174, 133, 20))
        self.lep6.setObjectName("lep6")
        self.lep7 = QtWidgets.QLineEdit(tela2)
        self.lep7.setGeometry(QtCore.QRect(290, 202, 133, 20))
        self.lep7.setObjectName("lep7")
        self.lep8 = QtWidgets.QLineEdit(tela2)
        self.lep8.setGeometry(QtCore.QRect(290, 231, 133, 20))
        self.lep8.setObjectName("lep8")
        self.label = QtWidgets.QLabel(tela2)
        self.label.setGeometry(QtCore.QRect(160, 26, 6, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(tela2)
        self.label_2.setGeometry(QtCore.QRect(160, 55, 6, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(tela2)
        self.label_3.setGeometry(QtCore.QRect(160, 84, 6, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(tela2)
        self.label_4.setGeometry(QtCore.QRect(160, 112, 6, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(tela2)
        self.label_5.setGeometry(QtCore.QRect(160, 143, 6, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(tela2)
        self.label_6.setGeometry(QtCore.QRect(160, 174, 6, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(tela2)
        self.label_7.setGeometry(QtCore.QRect(160, 201, 6, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(tela2)
        self.label_8.setGeometry(QtCore.QRect(160, 231, 6, 20))
        self.label_8.setObjectName("label_8")
        self.te_Dica = QtWidgets.QTextEdit(tela2)
        self.te_Dica.setGeometry(QtCore.QRect(20, 390, 661, 111))
        self.te_Dica.setObjectName("te_Dica")
        self.btn_acerto = QtWidgets.QPushButton(tela2)
        self.btn_acerto.setGeometry(QtCore.QRect(430, 27, 75, 23))
        self.btn_acerto.setObjectName("btn_acerto")
        self.btn_acerto_2 = QtWidgets.QPushButton(tela2)
        self.btn_acerto_2.setGeometry(QtCore.QRect(430, 56, 75, 23))
        self.btn_acerto_2.setObjectName("btn_acerto_2")
        self.btn_acerto_3 = QtWidgets.QPushButton(tela2)
        self.btn_acerto_3.setGeometry(QtCore.QRect(430, 85, 75, 23))
        self.btn_acerto_3.setObjectName("btn_acerto_3")
        self.btn_acerto_4 = QtWidgets.QPushButton(tela2)
        self.btn_acerto_4.setGeometry(QtCore.QRect(430, 114, 75, 23))
        self.btn_acerto_4.setObjectName("btn_acerto_4")
        self.btn_acerto_5 = QtWidgets.QPushButton(tela2)
        self.btn_acerto_5.setGeometry(QtCore.QRect(430, 143, 75, 23))
        self.btn_acerto_5.setObjectName("btn_acerto_5")
        self.btn_acerto_6 = QtWidgets.QPushButton(tela2)
        self.btn_acerto_6.setGeometry(QtCore.QRect(430, 172, 75, 23))
        self.btn_acerto_6.setObjectName("btn_acerto_6")
        self.btn_acerto_7 = QtWidgets.QPushButton(tela2)
        self.btn_acerto_7.setGeometry(QtCore.QRect(430, 201, 75, 23))
        self.btn_acerto_7.setObjectName("btn_acerto_7")
        self.btn_acerto_8 = QtWidgets.QPushButton(tela2)
        self.btn_acerto_8.setGeometry(QtCore.QRect(430, 230, 75, 23))
        self.btn_acerto_8.setObjectName("btn_acerto_8")
        self.j1 = QtWidgets.QLabel(tela2)
        self.j1.setGeometry(QtCore.QRect(180, 26, 111, 20))
        self.j1.setObjectName("j1")
        self.j8 = QtWidgets.QLabel(tela2)
        self.j8.setGeometry(QtCore.QRect(180, 231, 111, 20))
        self.j8.setObjectName("j8")
        self.j7 = QtWidgets.QLabel(tela2)
        self.j7.setGeometry(QtCore.QRect(180, 201, 111, 20))
        self.j7.setObjectName("j7")
        self.j4 = QtWidgets.QLabel(tela2)
        self.j4.setGeometry(QtCore.QRect(180, 112, 101, 20))
        self.j4.setObjectName("j4")
        self.j6 = QtWidgets.QLabel(tela2)
        self.j6.setGeometry(QtCore.QRect(180, 174, 101, 20))
        self.j6.setObjectName("j6")
        self.j3 = QtWidgets.QLabel(tela2)
        self.j3.setGeometry(QtCore.QRect(180, 84, 101, 20))
        self.j3.setObjectName("j3")
        self.j5 = QtWidgets.QLabel(tela2)
        self.j5.setGeometry(QtCore.QRect(180, 143, 101, 20))
        self.j5.setObjectName("j5")
        self.j2 = QtWidgets.QLabel(tela2)
        self.j2.setGeometry(QtCore.QRect(180, 55, 101, 20))
        self.j2.setObjectName("j2")
        self.j8_2 = QtWidgets.QLabel(tela2)
        self.j8_2.setGeometry(QtCore.QRect(30, 370, 91, 20))
        self.j8_2.setObjectName("j8_2")
        self.btn_carta = QtWidgets.QPushButton(tela2)
        self.btn_carta.setGeometry(QtCore.QRect(600, 350, 81, 31))
        self.btn_carta.setObjectName("btn_carta")
        self.j8_3 = QtWidgets.QLabel(tela2)
        self.j8_3.setGeometry(QtCore.QRect(30, 520, 91, 20))
        self.j8_3.setObjectName("j8_3")
        self.te_carta = QtWidgets.QTextEdit(tela2)
        self.te_carta.setGeometry(QtCore.QRect(20, 540, 661, 161))
        self.te_carta.setObjectName("te_carta")
        self.widget = QtWidgets.QWidget(tela2)
        self.widget.setGeometry(QtCore.QRect(10, 10, 77, 344))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_dica = QtWidgets.QPushButton(self.widget)
        self.btn_dica.setObjectName("btn_dica")
        self.verticalLayout_2.addWidget(self.btn_dica)
        self.btn_dica_2 = QtWidgets.QPushButton(self.widget)
        self.btn_dica_2.setObjectName("btn_dica_2")
        self.verticalLayout_2.addWidget(self.btn_dica_2)
        self.btn_dica_3 = QtWidgets.QPushButton(self.widget)
        self.btn_dica_3.setObjectName("btn_dica_3")
        self.verticalLayout_2.addWidget(self.btn_dica_3)
        self.btn_dica_4 = QtWidgets.QPushButton(self.widget)
        self.btn_dica_4.setObjectName("btn_dica_4")
        self.verticalLayout_2.addWidget(self.btn_dica_4)
        self.btn_dica_5 = QtWidgets.QPushButton(self.widget)
        self.btn_dica_5.setObjectName("btn_dica_5")
        self.verticalLayout_2.addWidget(self.btn_dica_5)
        self.btn_dica_6 = QtWidgets.QPushButton(self.widget)
        self.btn_dica_6.setObjectName("btn_dica_6")
        self.verticalLayout_2.addWidget(self.btn_dica_6)
        self.btn_dica_7 = QtWidgets.QPushButton(self.widget)
        self.btn_dica_7.setObjectName("btn_dica_7")
        self.verticalLayout_2.addWidget(self.btn_dica_7)
        self.btn_dica_8 = QtWidgets.QPushButton(self.widget)
        self.btn_dica_8.setObjectName("btn_dica_8")
        self.verticalLayout_2.addWidget(self.btn_dica_8)
        self.btn_dica_9 = QtWidgets.QPushButton(self.widget)
        self.btn_dica_9.setObjectName("btn_dica_9")
        self.verticalLayout_2.addWidget(self.btn_dica_9)
        self.btn_dica_10 = QtWidgets.QPushButton(self.widget)
        self.btn_dica_10.setObjectName("btn_dica_10")
        self.verticalLayout_2.addWidget(self.btn_dica_10)
        self.btn_dica_11 = QtWidgets.QPushButton(self.widget)
        self.btn_dica_11.setObjectName("btn_dica_11")
        self.verticalLayout_2.addWidget(self.btn_dica_11)
        self.btn_dica_12 = QtWidgets.QPushButton(self.widget)
        self.btn_dica_12.setObjectName("btn_dica_12")
        self.verticalLayout_2.addWidget(self.btn_dica_12)

        self.retranslateUi(tela2)
        QtCore.QMetaObject.connectSlotsByName(tela2)

    def retranslateUi(self, tela2):
        _translate = QtCore.QCoreApplication.translate
        tela2.setWindowTitle(_translate("tela2", "tela2"))
        self.label.setText(_translate("tela2", "1"))
        self.label_2.setText(_translate("tela2", "2"))
        self.label_3.setText(_translate("tela2", "3"))
        self.label_4.setText(_translate("tela2", "4"))
        self.label_5.setText(_translate("tela2", "5"))
        self.label_6.setText(_translate("tela2", "6"))
        self.label_7.setText(_translate("tela2", "7"))
        self.label_8.setText(_translate("tela2", "8"))
        self.te_Dica.setHtml(_translate("tela2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_acerto.setText(_translate("tela2", "Acertou"))
        self.btn_acerto_2.setText(_translate("tela2", "Acertou"))
        self.btn_acerto_3.setText(_translate("tela2", "Acertou"))
        self.btn_acerto_4.setText(_translate("tela2", "Acertou"))
        self.btn_acerto_5.setText(_translate("tela2", "Acertou"))
        self.btn_acerto_6.setText(_translate("tela2", "Acertou"))
        self.btn_acerto_7.setText(_translate("tela2", "Acertou"))
        self.btn_acerto_8.setText(_translate("tela2", "Acertou"))
        self.j1.setText(_translate("tela2", "Jogador 1"))
        self.j8.setText(_translate("tela2", "Jogador 8"))
        self.j7.setText(_translate("tela2", "Jogador 7"))
        self.j4.setText(_translate("tela2", "Jogador 4"))
        self.j6.setText(_translate("tela2", "Jogador 6"))
        self.j3.setText(_translate("tela2", "Jogador 3"))
        self.j5.setText(_translate("tela2", "Jogador 5"))
        self.j2.setText(_translate("tela2", "Jogador 2"))
        self.j8_2.setText(_translate("tela2", "Dica"))
        self.btn_carta.setText(_translate("tela2", "Carta"))
        self.j8_3.setText(_translate("tela2", "Carta"))
        self.te_carta.setHtml(_translate("tela2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_dica.setText(_translate("tela2", "D1"))
        self.btn_dica_2.setText(_translate("tela2", "D2"))
        self.btn_dica_3.setText(_translate("tela2", "D3"))
        self.btn_dica_4.setText(_translate("tela2", "D4"))
        self.btn_dica_5.setText(_translate("tela2", "D5"))
        self.btn_dica_6.setText(_translate("tela2", "D6"))
        self.btn_dica_7.setText(_translate("tela2", "D7"))
        self.btn_dica_8.setText(_translate("tela2", "D8"))
        self.btn_dica_9.setText(_translate("tela2", "D9"))
        self.btn_dica_10.setText(_translate("tela2", "D10"))
        self.btn_dica_11.setText(_translate("tela2", "D11"))
        self.btn_dica_12.setText(_translate("tela2", "D12"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela2 = QtWidgets.QDialog()
    ui = Ui_tela2()
    ui.setupUi(tela2)
    tela2.show()
    sys.exit(app.exec_())
