# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'perfildaergonomia.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PerfilErgonomia(object):
    def setupUi(self, PerfilErgonomia):
        PerfilErgonomia.setObjectName("PerfilErgonomia")
        PerfilErgonomia.resize(1280, 600)
        PerfilErgonomia.setMinimumSize(QtCore.QSize(1280, 600))
        PerfilErgonomia.setMaximumSize(QtCore.QSize(1280, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/ergonomia_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PerfilErgonomia.setWindowIcon(icon)
        PerfilErgonomia.setStyleSheet("")
        self.btnPontos = QtWidgets.QPushButton(PerfilErgonomia)
        self.btnPontos.setGeometry(QtCore.QRect(760, 537, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.btnPontos.setFont(font)
        self.btnPontos.setStyleSheet("QPushButton {\n"
"    color: rgb(220, 220, 220);\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(120,120,120);\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(220, 220, 220);\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(220, 220, 220);\n"
"    background-color: rgb(148,28,52);\n"
"    border: 3px solid rgb(239,184,16);\n"
"    border-radius: 5px\n"
"}")
        self.btnPontos.setObjectName("btnPontos")
        self.btnCarta = QtWidgets.QPushButton(PerfilErgonomia)
        self.btnCarta.setGeometry(QtCore.QRect(421, 537, 141, 41))
        self.btnCarta.setMinimumSize(QtCore.QSize(0, 0))
        self.btnCarta.setMaximumSize(QtCore.QSize(16666, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnCarta.setFont(font)
        self.btnCarta.setStyleSheet("QPushButton {\n"
"    color: rgb(220, 220, 220);\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(120,120,120);\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(220, 220, 220);\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(220, 220, 220);\n"
"    background-color: rgb(148,28,52);\n"
"    border: 3px solid rgb(239,184,16);\n"
"    border-radius: 5px\n"
"}")
        self.btnCarta.setObjectName("btnCarta")
        self.groupBox_3 = QtWidgets.QGroupBox(PerfilErgonomia)
        self.groupBox_3.setGeometry(QtCore.QRect(414, 56, 495, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.leJogador1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.leJogador1.setGeometry(QtCore.QRect(171, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador1.setFont(font)
        self.leJogador1.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador1.setObjectName("leJogador1")
        self.lePontJog1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lePontJog1.setGeometry(QtCore.QRect(341, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lePontJog1.setFont(font)
        self.lePontJog1.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.lePontJog1.setObjectName("lePontJog1")
        self.leJogador1_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.leJogador1_2.setGeometry(QtCore.QRect(8, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador1_2.setFont(font)
        self.leJogador1_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador1_2.setObjectName("leJogador1_2")
        self.groupBox_4 = QtWidgets.QGroupBox(PerfilErgonomia)
        self.groupBox_4.setGeometry(QtCore.QRect(569, 27, 171, 503))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.leJogador2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.leJogador2.setGeometry(QtCore.QRect(17, 102, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador2.setFont(font)
        self.leJogador2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador2.setObjectName("leJogador2")
        self.groupBox_5 = QtWidgets.QGroupBox(PerfilErgonomia)
        self.groupBox_5.setGeometry(QtCore.QRect(738, 27, 171, 503))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("QGroupBox{\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.lePontJog2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lePontJog2.setGeometry(QtCore.QRect(18, 102, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lePontJog2.setFont(font)
        self.lePontJog2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.lePontJog2.setObjectName("lePontJog2")
        self.groupBox_6 = QtWidgets.QGroupBox(PerfilErgonomia)
        self.groupBox_6.setGeometry(QtCore.QRect(414, 27, 157, 503))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("QGroupBox{\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.leJogador2_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.leJogador2_2.setGeometry(QtCore.QRect(10, 102, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador2_2.setFont(font)
        self.leJogador2_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador2_2.setObjectName("leJogador2_2")
        self.groupBox_7 = QtWidgets.QGroupBox(PerfilErgonomia)
        self.groupBox_7.setGeometry(QtCore.QRect(414, 115, 495, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("QGroupBox{\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_8 = QtWidgets.QGroupBox(PerfilErgonomia)
        self.groupBox_8.setGeometry(QtCore.QRect(414, 174, 495, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("QGroupBox{\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.leJogador3 = QtWidgets.QLineEdit(self.groupBox_8)
        self.leJogador3.setGeometry(QtCore.QRect(171, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador3.setFont(font)
        self.leJogador3.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador3.setObjectName("leJogador3")
        self.lePontJog3 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lePontJog3.setGeometry(QtCore.QRect(341, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lePontJog3.setFont(font)
        self.lePontJog3.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.lePontJog3.setObjectName("lePontJog3")
        self.leJogador2_3 = QtWidgets.QLineEdit(self.groupBox_8)
        self.leJogador2_3.setGeometry(QtCore.QRect(10, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador2_3.setFont(font)
        self.leJogador2_3.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador2_3.setObjectName("leJogador2_3")
        self.groupBox_9 = QtWidgets.QGroupBox(PerfilErgonomia)
        self.groupBox_9.setGeometry(QtCore.QRect(414, 233, 495, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet("QGroupBox{\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.leJogador4 = QtWidgets.QLineEdit(self.groupBox_9)
        self.leJogador4.setGeometry(QtCore.QRect(171, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador4.setFont(font)
        self.leJogador4.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador4.setObjectName("leJogador4")
        self.lePontJog4 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lePontJog4.setGeometry(QtCore.QRect(341, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lePontJog4.setFont(font)
        self.lePontJog4.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.lePontJog4.setObjectName("lePontJog4")
        self.leJogador2_4 = QtWidgets.QLineEdit(self.groupBox_9)
        self.leJogador2_4.setGeometry(QtCore.QRect(10, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador2_4.setFont(font)
        self.leJogador2_4.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador2_4.setObjectName("leJogador2_4")
        self.groupBox_10 = QtWidgets.QGroupBox(PerfilErgonomia)
        self.groupBox_10.setGeometry(QtCore.QRect(414, 292, 495, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setStyleSheet("QGroupBox{\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.leJogador5 = QtWidgets.QLineEdit(self.groupBox_10)
        self.leJogador5.setGeometry(QtCore.QRect(171, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador5.setFont(font)
        self.leJogador5.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador5.setObjectName("leJogador5")
        self.lePontJog5 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lePontJog5.setGeometry(QtCore.QRect(341, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lePontJog5.setFont(font)
        self.lePontJog5.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.lePontJog5.setObjectName("lePontJog5")
        self.leJogador2_5 = QtWidgets.QLineEdit(self.groupBox_10)
        self.leJogador2_5.setGeometry(QtCore.QRect(10, 15, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador2_5.setFont(font)
        self.leJogador2_5.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador2_5.setObjectName("leJogador2_5")
        self.groupBox_11 = QtWidgets.QGroupBox(PerfilErgonomia)
        self.groupBox_11.setGeometry(QtCore.QRect(414, 351, 495, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setStyleSheet("QGroupBox{\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.leJogador6 = QtWidgets.QLineEdit(self.groupBox_11)
        self.leJogador6.setGeometry(QtCore.QRect(171, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador6.setFont(font)
        self.leJogador6.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador6.setObjectName("leJogador6")
        self.lePontJog6 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lePontJog6.setGeometry(QtCore.QRect(341, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lePontJog6.setFont(font)
        self.lePontJog6.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.lePontJog6.setObjectName("lePontJog6")
        self.leJogador2_6 = QtWidgets.QLineEdit(self.groupBox_11)
        self.leJogador2_6.setGeometry(QtCore.QRect(10, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador2_6.setFont(font)
        self.leJogador2_6.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador2_6.setObjectName("leJogador2_6")
        self.groupBox_12 = QtWidgets.QGroupBox(PerfilErgonomia)
        self.groupBox_12.setGeometry(QtCore.QRect(414, 410, 495, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setStyleSheet("QGroupBox{\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.leJogador7 = QtWidgets.QLineEdit(self.groupBox_12)
        self.leJogador7.setGeometry(QtCore.QRect(171, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador7.setFont(font)
        self.leJogador7.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador7.setObjectName("leJogador7")
        self.lePontJog7 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lePontJog7.setGeometry(QtCore.QRect(341, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lePontJog7.setFont(font)
        self.lePontJog7.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.lePontJog7.setObjectName("lePontJog7")
        self.leJogador2_7 = QtWidgets.QLineEdit(self.groupBox_12)
        self.leJogador2_7.setGeometry(QtCore.QRect(9, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador2_7.setFont(font)
        self.leJogador2_7.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador2_7.setObjectName("leJogador2_7")
        self.groupBox_13 = QtWidgets.QGroupBox(PerfilErgonomia)
        self.groupBox_13.setGeometry(QtCore.QRect(414, 469, 495, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setStyleSheet("QGroupBox{\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.leJogador8 = QtWidgets.QLineEdit(self.groupBox_13)
        self.leJogador8.setGeometry(QtCore.QRect(171, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador8.setFont(font)
        self.leJogador8.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador8.setObjectName("leJogador8")
        self.lePontJog8 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lePontJog8.setGeometry(QtCore.QRect(341, 14, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lePontJog8.setFont(font)
        self.lePontJog8.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.lePontJog8.setObjectName("lePontJog8")
        self.leJogador2_8 = QtWidgets.QLineEdit(self.groupBox_13)
        self.leJogador2_8.setGeometry(QtCore.QRect(10, 13, 141, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.leJogador2_8.setFont(font)
        self.leJogador2_8.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    backgroud-color: rgb(30,30,30);\n"
"    color: rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(148,28,52);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.leJogador2_8.setObjectName("leJogador2_8")
        self.groupBox_17 = QtWidgets.QGroupBox(PerfilErgonomia)
        self.groupBox_17.setGeometry(QtCore.QRect(414, 27, 495, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setStyleSheet("QGroupBox{\n"
"    border: 2px solid rgb(0,0,0);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.groupBox_17.setTitle("")
        self.groupBox_17.setObjectName("groupBox_17")
        self.lblJogador8_2 = QtWidgets.QLabel(self.groupBox_17)
        self.lblJogador8_2.setGeometry(QtCore.QRect(2, 1, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lblJogador8_2.setFont(font)
        self.lblJogador8_2.setStyleSheet("QLabel {\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    color: 2px solid rgb(20,20,253);\n"
"}\n"
"\n"
"")
        self.lblJogador8_2.setObjectName("lblJogador8_2")
        self.lblJogador8_3 = QtWidgets.QLabel(self.groupBox_17)
        self.lblJogador8_3.setGeometry(QtCore.QRect(160, 0, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lblJogador8_3.setFont(font)
        self.lblJogador8_3.setStyleSheet("QLabel {\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    color: 2px solid rgb(20,20,253);\n"
"}\n"
"\n"
"")
        self.lblJogador8_3.setObjectName("lblJogador8_3")
        self.lblJogador8_4 = QtWidgets.QLabel(self.groupBox_17)
        self.lblJogador8_4.setGeometry(QtCore.QRect(329, 0, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lblJogador8_4.setFont(font)
        self.lblJogador8_4.setStyleSheet("QLabel {\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    color: 2px solid rgb(20,20,253);\n"
"}\n"
"\n"
"")
        self.lblJogador8_4.setObjectName("lblJogador8_4")
        self.frame = QtWidgets.QFrame(PerfilErgonomia)
        self.frame.setGeometry(QtCore.QRect(-130, -85, 1541, 771))
        self.frame.setStyleSheet("image: url(:/img/img/TabuleiroTabelaEscuro1280x600.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnAtualizaPontos = QtWidgets.QPushButton(PerfilErgonomia)
        self.btnAtualizaPontos.setGeometry(QtCore.QRect(589, 537, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.btnAtualizaPontos.setFont(font)
        self.btnAtualizaPontos.setStyleSheet("QPushButton {\n"
"    color: rgb(220, 220, 220);\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(120,120,120);\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(220, 220, 220);\n"
"    border: 2px solid rgb(148,28,52);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(220, 220, 220);\n"
"    background-color: rgb(148,28,52);\n"
"    border: 3px solid rgb(239,184,16);\n"
"    border-radius: 5px\n"
"}")
        self.btnAtualizaPontos.setObjectName("btnAtualizaPontos")
        self.frame.raise_()
        self.groupBox_7.raise_()
        self.groupBox_6.raise_()
        self.groupBox_5.raise_()
        self.groupBox_4.raise_()
        self.btnPontos.raise_()
        self.btnCarta.raise_()
        self.groupBox_3.raise_()
        self.groupBox_8.raise_()
        self.groupBox_9.raise_()
        self.groupBox_10.raise_()
        self.groupBox_11.raise_()
        self.groupBox_12.raise_()
        self.groupBox_13.raise_()
        self.groupBox_17.raise_()
        self.btnAtualizaPontos.raise_()

        self.retranslateUi(PerfilErgonomia)
        QtCore.QMetaObject.connectSlotsByName(PerfilErgonomia)

    def retranslateUi(self, PerfilErgonomia):
        _translate = QtCore.QCoreApplication.translate
        PerfilErgonomia.setWindowTitle(_translate("PerfilErgonomia", "Perfil Da Ergonomia"))
        self.btnPontos.setText(_translate("PerfilErgonomia", "Enviar Pontuação"))
        self.btnCarta.setText(_translate("PerfilErgonomia", "Tirar Carta"))
        self.leJogador1.setPlaceholderText(_translate("PerfilErgonomia", "Pontos"))
        self.lePontJog1.setPlaceholderText(_translate("PerfilErgonomia", "Inserir pontuação"))
        self.leJogador1_2.setPlaceholderText(_translate("PerfilErgonomia", "Jogador 1"))
        self.leJogador2.setPlaceholderText(_translate("PerfilErgonomia", "Pontos"))
        self.lePontJog2.setPlaceholderText(_translate("PerfilErgonomia", "Inserir pontuação"))
        self.leJogador2_2.setPlaceholderText(_translate("PerfilErgonomia", "Jogador 2"))
        self.leJogador3.setPlaceholderText(_translate("PerfilErgonomia", "Pontos"))
        self.lePontJog3.setPlaceholderText(_translate("PerfilErgonomia", "Inserir pontuação"))
        self.leJogador2_3.setPlaceholderText(_translate("PerfilErgonomia", "Jogador 3"))
        self.leJogador4.setPlaceholderText(_translate("PerfilErgonomia", "Pontos"))
        self.lePontJog4.setPlaceholderText(_translate("PerfilErgonomia", "Inserir pontuação"))
        self.leJogador2_4.setPlaceholderText(_translate("PerfilErgonomia", "Jogador 4"))
        self.leJogador5.setPlaceholderText(_translate("PerfilErgonomia", "Pontos"))
        self.lePontJog5.setPlaceholderText(_translate("PerfilErgonomia", "Inserir pontuação"))
        self.leJogador2_5.setPlaceholderText(_translate("PerfilErgonomia", "Jogador 5"))
        self.leJogador6.setPlaceholderText(_translate("PerfilErgonomia", "Pontos"))
        self.lePontJog6.setPlaceholderText(_translate("PerfilErgonomia", "Inserir pontuação"))
        self.leJogador2_6.setPlaceholderText(_translate("PerfilErgonomia", "Jogador 6"))
        self.leJogador7.setPlaceholderText(_translate("PerfilErgonomia", "Pontos"))
        self.lePontJog7.setPlaceholderText(_translate("PerfilErgonomia", "Inserir pontuação"))
        self.leJogador2_7.setPlaceholderText(_translate("PerfilErgonomia", "Jogador 7"))
        self.leJogador8.setPlaceholderText(_translate("PerfilErgonomia", "Pontos"))
        self.lePontJog8.setPlaceholderText(_translate("PerfilErgonomia", "Inserir pontuação"))
        self.leJogador2_8.setPlaceholderText(_translate("PerfilErgonomia", "Jogador 8"))
        self.lblJogador8_2.setText(_translate("PerfilErgonomia", "<html><head/><body><p align=\"center\">Jogadores</p></body></html>"))
        self.lblJogador8_3.setText(_translate("PerfilErgonomia", "<html><head/><body><p align=\"center\">Pontuação Total</p></body></html>"))
        self.lblJogador8_4.setText(_translate("PerfilErgonomia", "<html><head/><body><p align=\"center\">Pontos da Rodada</p></body></html>"))
        self.btnAtualizaPontos.setText(_translate("PerfilErgonomia", "Atualizar Pontos"))
from template import img